from os import getenv

DEFAULT_EMBED_MODEL = getenv('PYTHON_AI_EMBED_MODEL_ID', 'sentence-transformers/all-MiniLM-L6-v2')
DEFAULT_CHAT_MODEL = getenv('PYTHON_AI_CHAT_MODEL_ID', 'Qwen/Qwen2.5-1.5B-Instruct')
DEFAULT_DEVICE = getenv('PYTHON_AI_DEVICE', 'cpu')
DEFAULT_DTYPE = getenv('PYTHON_AI_DTYPE', 'float32')
DEFAULT_MAX_NEW_TOKENS = int(getenv('PYTHON_AI_MAX_NEW_TOKENS', '256'))
DEFAULT_TEMPERATURE = float(getenv('PYTHON_AI_TEMPERATURE', '0.2'))
DEFAULT_TOP_P = float(getenv('PYTHON_AI_TOP_P', '0.9'))
DEFAULT_MAX_INPUT_CHARS = 12000
OCR_MIN_CONFIDENCE = float(getenv('PYTHON_AI_OCR_MIN_CONFIDENCE', '0.2'))
OCR_MIN_TEXT_LENGTH = int(getenv('PYTHON_AI_OCR_MIN_TEXT_LENGTH', '32'))
OCR_RENDER_ZOOM = float(getenv('PYTHON_AI_OCR_RENDER_ZOOM', '2.0'))
OCR_MAX_PAGES = int(getenv('PYTHON_AI_OCR_MAX_PAGES', '20'))
OCR_MAX_FILE_BYTES = int(getenv('PYTHON_AI_OCR_MAX_FILE_BYTES', '15728640'))
OCR_MIN_OUTPUT_CHARS = int(getenv('PYTHON_AI_OCR_MIN_OUTPUT_CHARS', '16'))
GENERATION_MIN_CONFIDENCE = float(getenv('PYTHON_AI_GENERATION_MIN_CONFIDENCE', '0.65'))
GENERATION_MAX_OUTPUT_CHARS = int(getenv('PYTHON_AI_GENERATION_MAX_OUTPUT_CHARS', '1200'))
GENERATION_MAX_SOURCE_ITEMS = int(getenv('PYTHON_AI_GENERATION_MAX_SOURCE_ITEMS', '12'))
